name: Docker Image CI for the Hashing and Web Scraping python services

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [hashing-service, web-scraping-service]
        python-version: [3.11.2]
          
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Set Python path to root directory
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        
    - name: Build and test ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r ../requirements.txt
        python -m pytest -v
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.DOCKER_USERNAME }}/${{ matrix.service }}
      
    - name: Build and tag Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.service-name }}
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ matrix.service }}:$(date +%s)

    - name: Push metadata to Docker Hub
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.DOCKER_USERNAME }}/${{ matrix.service }}:$(date +%s)
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
